package layout

// Code generated from ratatui 0.30.2 letter tables. DO NOT EDIT by hand.

var letterCorpusData = []letterCase{
	{FlexLegacy, 1, []Constraint{Length(0)}, "a"},
	{FlexLegacy, 1, []Constraint{Length(1)}, "a"},
	{FlexLegacy, 1, []Constraint{Length(2)}, "a"},
	{FlexLegacy, 2, []Constraint{Length(0)}, "aa"},
	{FlexLegacy, 2, []Constraint{Length(1)}, "aa"},
	{FlexLegacy, 2, []Constraint{Length(2)}, "aa"},
	{FlexLegacy, 2, []Constraint{Length(3)}, "aa"},
	{FlexLegacy, 1, []Constraint{Length(0), Length(0)}, "b"},
	{FlexLegacy, 1, []Constraint{Length(0), Length(1)}, "b"},
	{FlexLegacy, 1, []Constraint{Length(0), Length(2)}, "b"},
	{FlexLegacy, 1, []Constraint{Length(1), Length(0)}, "a"},
	{FlexLegacy, 1, []Constraint{Length(1), Length(1)}, "a"},
	{FlexLegacy, 1, []Constraint{Length(1), Length(2)}, "a"},
	{FlexLegacy, 1, []Constraint{Length(2), Length(0)}, "a"},
	{FlexLegacy, 1, []Constraint{Length(2), Length(1)}, "a"},
	{FlexLegacy, 1, []Constraint{Length(2), Length(2)}, "a"},
	{FlexLegacy, 2, []Constraint{Length(0), Length(0)}, "bb"},
	{FlexLegacy, 2, []Constraint{Length(0), Length(1)}, "bb"},
	{FlexLegacy, 2, []Constraint{Length(0), Length(2)}, "bb"},
	{FlexLegacy, 2, []Constraint{Length(0), Length(3)}, "bb"},
	{FlexLegacy, 2, []Constraint{Length(1), Length(0)}, "ab"},
	{FlexLegacy, 2, []Constraint{Length(1), Length(1)}, "ab"},
	{FlexLegacy, 2, []Constraint{Length(1), Length(2)}, "ab"},
	{FlexLegacy, 2, []Constraint{Length(1), Length(3)}, "ab"},
	{FlexLegacy, 2, []Constraint{Length(2), Length(0)}, "aa"},
	{FlexLegacy, 2, []Constraint{Length(2), Length(1)}, "aa"},
	{FlexLegacy, 2, []Constraint{Length(2), Length(2)}, "aa"},
	{FlexLegacy, 2, []Constraint{Length(2), Length(3)}, "aa"},
	{FlexLegacy, 2, []Constraint{Length(3), Length(0)}, "aa"},
	{FlexLegacy, 2, []Constraint{Length(3), Length(1)}, "aa"},
	{FlexLegacy, 2, []Constraint{Length(3), Length(2)}, "aa"},
	{FlexLegacy, 2, []Constraint{Length(3), Length(3)}, "aa"},
	{FlexLegacy, 3, []Constraint{Length(2), Length(2)}, "aab"},
	{FlexLegacy, 1, []Constraint{Max(0)}, "a"},
	{FlexLegacy, 1, []Constraint{Max(1)}, "a"},
	{FlexLegacy, 1, []Constraint{Max(2)}, "a"},
	{FlexLegacy, 2, []Constraint{Max(0)}, "aa"},
	{FlexLegacy, 2, []Constraint{Max(1)}, "aa"},
	{FlexLegacy, 2, []Constraint{Max(2)}, "aa"},
	{FlexLegacy, 2, []Constraint{Max(3)}, "aa"},
	{FlexLegacy, 1, []Constraint{Max(0), Max(0)}, "b"},
	{FlexLegacy, 1, []Constraint{Max(0), Max(1)}, "b"},
	{FlexLegacy, 1, []Constraint{Max(0), Max(2)}, "b"},
	{FlexLegacy, 1, []Constraint{Max(1), Max(0)}, "a"},
	{FlexLegacy, 1, []Constraint{Max(1), Max(1)}, "a"},
	{FlexLegacy, 1, []Constraint{Max(1), Max(2)}, "a"},
	{FlexLegacy, 1, []Constraint{Max(2), Max(0)}, "a"},
	{FlexLegacy, 1, []Constraint{Max(2), Max(1)}, "a"},
	{FlexLegacy, 1, []Constraint{Max(2), Max(2)}, "a"},
	{FlexLegacy, 2, []Constraint{Max(0), Max(0)}, "bb"},
	{FlexLegacy, 2, []Constraint{Max(0), Max(1)}, "bb"},
	{FlexLegacy, 2, []Constraint{Max(0), Max(2)}, "bb"},
	{FlexLegacy, 2, []Constraint{Max(0), Max(3)}, "bb"},
	{FlexLegacy, 2, []Constraint{Max(1), Max(0)}, "ab"},
	{FlexLegacy, 2, []Constraint{Max(1), Max(1)}, "ab"},
	{FlexLegacy, 2, []Constraint{Max(1), Max(2)}, "ab"},
	{FlexLegacy, 2, []Constraint{Max(1), Max(3)}, "ab"},
	{FlexLegacy, 2, []Constraint{Max(2), Max(0)}, "aa"},
	{FlexLegacy, 2, []Constraint{Max(2), Max(1)}, "aa"},
	{FlexLegacy, 2, []Constraint{Max(2), Max(2)}, "aa"},
	{FlexLegacy, 2, []Constraint{Max(2), Max(3)}, "aa"},
	{FlexLegacy, 2, []Constraint{Max(3), Max(0)}, "aa"},
	{FlexLegacy, 2, []Constraint{Max(3), Max(1)}, "aa"},
	{FlexLegacy, 2, []Constraint{Max(3), Max(2)}, "aa"},
	{FlexLegacy, 2, []Constraint{Max(3), Max(3)}, "aa"},
	{FlexLegacy, 3, []Constraint{Max(2), Max(2)}, "aab"},
	{FlexLegacy, 1, []Constraint{Min(0), Min(0)}, "b"},
	{FlexLegacy, 1, []Constraint{Min(0), Min(1)}, "b"},
	{FlexLegacy, 1, []Constraint{Min(0), Min(2)}, "b"},
	{FlexLegacy, 1, []Constraint{Min(1), Min(0)}, "a"},
	{FlexLegacy, 1, []Constraint{Min(1), Min(1)}, "a"},
	{FlexLegacy, 1, []Constraint{Min(1), Min(2)}, "a"},
	{FlexLegacy, 1, []Constraint{Min(2), Min(0)}, "a"},
	{FlexLegacy, 1, []Constraint{Min(2), Min(1)}, "a"},
	{FlexLegacy, 1, []Constraint{Min(2), Min(2)}, "a"},
	{FlexLegacy, 2, []Constraint{Min(0), Min(0)}, "bb"},
	{FlexLegacy, 2, []Constraint{Min(0), Min(1)}, "bb"},
	{FlexLegacy, 2, []Constraint{Min(0), Min(2)}, "bb"},
	{FlexLegacy, 2, []Constraint{Min(0), Min(3)}, "bb"},
	{FlexLegacy, 2, []Constraint{Min(1), Min(0)}, "ab"},
	{FlexLegacy, 2, []Constraint{Min(1), Min(1)}, "ab"},
	{FlexLegacy, 2, []Constraint{Min(1), Min(2)}, "ab"},
	{FlexLegacy, 2, []Constraint{Min(1), Min(3)}, "ab"},
	{FlexLegacy, 2, []Constraint{Min(2), Min(0)}, "aa"},
	{FlexLegacy, 2, []Constraint{Min(2), Min(1)}, "aa"},
	{FlexLegacy, 2, []Constraint{Min(2), Min(2)}, "aa"},
	{FlexLegacy, 2, []Constraint{Min(2), Min(3)}, "aa"},
	{FlexLegacy, 2, []Constraint{Min(3), Min(0)}, "aa"},
	{FlexLegacy, 2, []Constraint{Min(3), Min(1)}, "aa"},
	{FlexLegacy, 2, []Constraint{Min(3), Min(2)}, "aa"},
	{FlexLegacy, 2, []Constraint{Min(3), Min(3)}, "aa"},
	{FlexLegacy, 3, []Constraint{Min(2), Min(2)}, "aab"},
	{FlexLegacy, 1, []Constraint{Percentage(0)}, "a"},
	{FlexLegacy, 1, []Constraint{Percentage(25)}, "a"},
	{FlexLegacy, 1, []Constraint{Percentage(50)}, "a"},
	{FlexLegacy, 1, []Constraint{Percentage(90)}, "a"},
	{FlexLegacy, 1, []Constraint{Percentage(100)}, "a"},
	{FlexLegacy, 1, []Constraint{Percentage(200)}, "a"},
	{FlexLegacy, 2, []Constraint{Percentage(0)}, "aa"},
	{FlexLegacy, 2, []Constraint{Percentage(10)}, "aa"},
	{FlexLegacy, 2, []Constraint{Percentage(25)}, "aa"},
	{FlexLegacy, 2, []Constraint{Percentage(50)}, "aa"},
	{FlexLegacy, 2, []Constraint{Percentage(66)}, "aa"},
	{FlexLegacy, 2, []Constraint{Percentage(100)}, "aa"},
	{FlexLegacy, 2, []Constraint{Percentage(200)}, "aa"},
	{FlexLegacy, 10, []Constraint{Percentage(0)}, "aaaaaaaaaa"},
	{FlexLegacy, 10, []Constraint{Percentage(10)}, "aaaaaaaaaa"},
	{FlexLegacy, 10, []Constraint{Percentage(25)}, "aaaaaaaaaa"},
	{FlexLegacy, 10, []Constraint{Percentage(50)}, "aaaaaaaaaa"},
	{FlexLegacy, 10, []Constraint{Percentage(66)}, "aaaaaaaaaa"},
	{FlexLegacy, 10, []Constraint{Percentage(100)}, "aaaaaaaaaa"},
	{FlexLegacy, 10, []Constraint{Percentage(200)}, "aaaaaaaaaa"},
	{FlexLegacy, 1, []Constraint{Percentage(0), Percentage(0)}, "b"},
	{FlexLegacy, 1, []Constraint{Percentage(0), Percentage(10)}, "b"},
	{FlexLegacy, 1, []Constraint{Percentage(0), Percentage(50)}, "b"},
	{FlexLegacy, 1, []Constraint{Percentage(0), Percentage(90)}, "b"},
	{FlexLegacy, 1, []Constraint{Percentage(0), Percentage(100)}, "b"},
	{FlexLegacy, 1, []Constraint{Percentage(0), Percentage(200)}, "b"},
	{FlexLegacy, 1, []Constraint{Percentage(10), Percentage(0)}, "b"},
	{FlexLegacy, 1, []Constraint{Percentage(10), Percentage(10)}, "b"},
	{FlexLegacy, 1, []Constraint{Percentage(10), Percentage(50)}, "b"},
	{FlexLegacy, 1, []Constraint{Percentage(10), Percentage(90)}, "b"},
	{FlexLegacy, 1, []Constraint{Percentage(10), Percentage(100)}, "b"},
	{FlexLegacy, 1, []Constraint{Percentage(10), Percentage(200)}, "b"},
	{FlexLegacy, 1, []Constraint{Percentage(50), Percentage(0)}, "a"},
	{FlexLegacy, 1, []Constraint{Percentage(50), Percentage(50)}, "a"},
	{FlexLegacy, 1, []Constraint{Percentage(50), Percentage(100)}, "a"},
	{FlexLegacy, 1, []Constraint{Percentage(50), Percentage(200)}, "a"},
	{FlexLegacy, 1, []Constraint{Percentage(90), Percentage(0)}, "a"},
	{FlexLegacy, 1, []Constraint{Percentage(90), Percentage(50)}, "a"},
	{FlexLegacy, 1, []Constraint{Percentage(90), Percentage(100)}, "a"},
	{FlexLegacy, 1, []Constraint{Percentage(90), Percentage(200)}, "a"},
	{FlexLegacy, 1, []Constraint{Percentage(100), Percentage(0)}, "a"},
	{FlexLegacy, 1, []Constraint{Percentage(100), Percentage(50)}, "a"},
	{FlexLegacy, 1, []Constraint{Percentage(100), Percentage(100)}, "a"},
	{FlexLegacy, 1, []Constraint{Percentage(100), Percentage(200)}, "a"},
	{FlexLegacy, 2, []Constraint{Percentage(0), Percentage(0)}, "bb"},
	{FlexLegacy, 2, []Constraint{Percentage(0), Percentage(25)}, "bb"},
	{FlexLegacy, 2, []Constraint{Percentage(0), Percentage(50)}, "bb"},
	{FlexLegacy, 2, []Constraint{Percentage(0), Percentage(100)}, "bb"},
	{FlexLegacy, 2, []Constraint{Percentage(0), Percentage(200)}, "bb"},
	{FlexLegacy, 2, []Constraint{Percentage(10), Percentage(0)}, "bb"},
	{FlexLegacy, 2, []Constraint{Percentage(10), Percentage(25)}, "bb"},
	{FlexLegacy, 2, []Constraint{Percentage(10), Percentage(50)}, "bb"},
	{FlexLegacy, 2, []Constraint{Percentage(10), Percentage(100)}, "bb"},
	{FlexLegacy, 2, []Constraint{Percentage(10), Percentage(200)}, "bb"},
	{FlexLegacy, 2, []Constraint{Percentage(25), Percentage(0)}, "ab"},
	{FlexLegacy, 2, []Constraint{Percentage(25), Percentage(25)}, "ab"},
	{FlexLegacy, 2, []Constraint{Percentage(25), Percentage(50)}, "ab"},
	{FlexLegacy, 2, []Constraint{Percentage(25), Percentage(100)}, "ab"},
	{FlexLegacy, 2, []Constraint{Percentage(25), Percentage(200)}, "ab"},
	{FlexLegacy, 2, []Constraint{Percentage(33), Percentage(0)}, "ab"},
	{FlexLegacy, 2, []Constraint{Percentage(33), Percentage(25)}, "ab"},
	{FlexLegacy, 2, []Constraint{Percentage(33), Percentage(50)}, "ab"},
	{FlexLegacy, 2, []Constraint{Percentage(33), Percentage(100)}, "ab"},
	{FlexLegacy, 2, []Constraint{Percentage(33), Percentage(200)}, "ab"},
	{FlexLegacy, 2, []Constraint{Percentage(50), Percentage(0)}, "ab"},
	{FlexLegacy, 2, []Constraint{Percentage(50), Percentage(50)}, "ab"},
	{FlexLegacy, 2, []Constraint{Percentage(50), Percentage(100)}, "ab"},
	{FlexLegacy, 2, []Constraint{Percentage(100), Percentage(0)}, "aa"},
	{FlexLegacy, 2, []Constraint{Percentage(100), Percentage(50)}, "aa"},
	{FlexLegacy, 2, []Constraint{Percentage(100), Percentage(100)}, "aa"},
	{FlexLegacy, 3, []Constraint{Percentage(33), Percentage(33)}, "abb"},
	{FlexLegacy, 3, []Constraint{Percentage(33), Percentage(66)}, "abb"},
	{FlexLegacy, 4, []Constraint{Percentage(33), Percentage(33)}, "abbb"},
	{FlexLegacy, 4, []Constraint{Percentage(33), Percentage(66)}, "abbb"},
	{FlexLegacy, 10, []Constraint{Percentage(0), Percentage(0)}, "bbbbbbbbbb"},
	{FlexLegacy, 10, []Constraint{Percentage(0), Percentage(25)}, "bbbbbbbbbb"},
	{FlexLegacy, 10, []Constraint{Percentage(0), Percentage(50)}, "bbbbbbbbbb"},
	{FlexLegacy, 10, []Constraint{Percentage(0), Percentage(100)}, "bbbbbbbbbb"},
	{FlexLegacy, 10, []Constraint{Percentage(0), Percentage(200)}, "bbbbbbbbbb"},
	{FlexLegacy, 10, []Constraint{Percentage(10), Percentage(0)}, "abbbbbbbbb"},
	{FlexLegacy, 10, []Constraint{Percentage(10), Percentage(25)}, "abbbbbbbbb"},
	{FlexLegacy, 10, []Constraint{Percentage(10), Percentage(50)}, "abbbbbbbbb"},
	{FlexLegacy, 10, []Constraint{Percentage(10), Percentage(100)}, "abbbbbbbbb"},
	{FlexLegacy, 10, []Constraint{Percentage(10), Percentage(200)}, "abbbbbbbbb"},
	{FlexLegacy, 10, []Constraint{Percentage(25), Percentage(0)}, "aaabbbbbbb"},
	{FlexLegacy, 10, []Constraint{Percentage(25), Percentage(25)}, "aaabbbbbbb"},
	{FlexLegacy, 10, []Constraint{Percentage(25), Percentage(50)}, "aaabbbbbbb"},
	{FlexLegacy, 10, []Constraint{Percentage(25), Percentage(100)}, "aaabbbbbbb"},
	{FlexLegacy, 10, []Constraint{Percentage(25), Percentage(200)}, "aaabbbbbbb"},
	{FlexLegacy, 10, []Constraint{Percentage(33), Percentage(0)}, "aaabbbbbbb"},
	{FlexLegacy, 10, []Constraint{Percentage(33), Percentage(25)}, "aaabbbbbbb"},
	{FlexLegacy, 10, []Constraint{Percentage(33), Percentage(50)}, "aaabbbbbbb"},
	{FlexLegacy, 10, []Constraint{Percentage(33), Percentage(100)}, "aaabbbbbbb"},
	{FlexLegacy, 10, []Constraint{Percentage(33), Percentage(200)}, "aaabbbbbbb"},
	{FlexLegacy, 10, []Constraint{Percentage(50), Percentage(0)}, "aaaaabbbbb"},
	{FlexLegacy, 10, []Constraint{Percentage(50), Percentage(50)}, "aaaaabbbbb"},
	{FlexLegacy, 10, []Constraint{Percentage(50), Percentage(100)}, "aaaaabbbbb"},
	{FlexLegacy, 10, []Constraint{Percentage(100), Percentage(0)}, "aaaaaaaaaa"},
	{FlexLegacy, 10, []Constraint{Percentage(100), Percentage(50)}, "aaaaaaaaaa"},
	{FlexLegacy, 10, []Constraint{Percentage(100), Percentage(100)}, "aaaaaaaaaa"},
	{FlexStart, 10, []Constraint{Percentage(0), Percentage(0)}, "          "},
	{FlexStart, 10, []Constraint{Percentage(0), Percentage(25)}, "bbb       "},
	{FlexStart, 10, []Constraint{Percentage(0), Percentage(50)}, "bbbbb     "},
	{FlexStart, 10, []Constraint{Percentage(0), Percentage(100)}, "bbbbbbbbbb"},
	{FlexStart, 10, []Constraint{Percentage(0), Percentage(200)}, "bbbbbbbbbb"},
	{FlexStart, 10, []Constraint{Percentage(10), Percentage(0)}, "a         "},
	{FlexStart, 10, []Constraint{Percentage(10), Percentage(25)}, "abbb      "},
	{FlexStart, 10, []Constraint{Percentage(10), Percentage(50)}, "abbbbb    "},
	{FlexStart, 10, []Constraint{Percentage(10), Percentage(100)}, "abbbbbbbbb"},
	{FlexStart, 10, []Constraint{Percentage(10), Percentage(200)}, "abbbbbbbbb"},
	{FlexStart, 10, []Constraint{Percentage(25), Percentage(0)}, "aaa       "},
	{FlexStart, 10, []Constraint{Percentage(25), Percentage(25)}, "aaabb     "},
	{FlexStart, 10, []Constraint{Percentage(25), Percentage(50)}, "aaabbbbb  "},
	{FlexStart, 10, []Constraint{Percentage(25), Percentage(100)}, "aaabbbbbbb"},
	{FlexStart, 10, []Constraint{Percentage(25), Percentage(200)}, "aaabbbbbbb"},
	{FlexStart, 10, []Constraint{Percentage(33), Percentage(0)}, "aaa       "},
	{FlexStart, 10, []Constraint{Percentage(33), Percentage(25)}, "aaabbb    "},
	{FlexStart, 10, []Constraint{Percentage(33), Percentage(50)}, "aaabbbbb  "},
	{FlexStart, 10, []Constraint{Percentage(33), Percentage(100)}, "aaabbbbbbb"},
	{FlexStart, 10, []Constraint{Percentage(33), Percentage(200)}, "aaabbbbbbb"},
	{FlexStart, 10, []Constraint{Percentage(50), Percentage(0)}, "aaaaa     "},
	{FlexStart, 10, []Constraint{Percentage(50), Percentage(50)}, "aaaaabbbbb"},
	{FlexStart, 10, []Constraint{Percentage(50), Percentage(100)}, "aaaaabbbbb"},
	{FlexStart, 10, []Constraint{Percentage(100), Percentage(0)}, "aaaaaaaaaa"},
	{FlexStart, 10, []Constraint{Percentage(100), Percentage(50)}, "aaaaabbbbb"},
	{FlexStart, 10, []Constraint{Percentage(100), Percentage(100)}, "aaaaabbbbb"},
	{FlexStart, 10, []Constraint{Percentage(100), Percentage(200)}, "aaaaabbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Percentage(0), Percentage(0)}, "          "},
	{FlexSpaceBetween, 10, []Constraint{Percentage(0), Percentage(25)}, "        bb"},
	{FlexSpaceBetween, 10, []Constraint{Percentage(0), Percentage(50)}, "     bbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Percentage(0), Percentage(100)}, "bbbbbbbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Percentage(0), Percentage(200)}, "bbbbbbbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Percentage(10), Percentage(0)}, "a         "},
	{FlexSpaceBetween, 10, []Constraint{Percentage(10), Percentage(25)}, "a       bb"},
	{FlexSpaceBetween, 10, []Constraint{Percentage(10), Percentage(50)}, "a    bbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Percentage(10), Percentage(100)}, "abbbbbbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Percentage(10), Percentage(200)}, "abbbbbbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Percentage(25), Percentage(0)}, "aaa       "},
	{FlexSpaceBetween, 10, []Constraint{Percentage(25), Percentage(25)}, "aaa     bb"},
	{FlexSpaceBetween, 10, []Constraint{Percentage(25), Percentage(50)}, "aaa  bbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Percentage(25), Percentage(100)}, "aaabbbbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Percentage(25), Percentage(200)}, "aaabbbbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Percentage(33), Percentage(0)}, "aaa       "},
	{FlexSpaceBetween, 10, []Constraint{Percentage(33), Percentage(25)}, "aaa     bb"},
	{FlexSpaceBetween, 10, []Constraint{Percentage(33), Percentage(50)}, "aaa  bbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Percentage(33), Percentage(100)}, "aaabbbbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Percentage(33), Percentage(200)}, "aaabbbbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Percentage(50), Percentage(0)}, "aaaaa     "},
	{FlexSpaceBetween, 10, []Constraint{Percentage(50), Percentage(50)}, "aaaaabbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Percentage(50), Percentage(100)}, "aaaaabbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Percentage(100), Percentage(0)}, "aaaaaaaaaa"},
	{FlexSpaceBetween, 10, []Constraint{Percentage(100), Percentage(50)}, "aaaaabbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Percentage(100), Percentage(100)}, "aaaaabbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Percentage(100), Percentage(200)}, "aaaaabbbbb"},
	{FlexLegacy, 1, []Constraint{Ratio(0, 1)}, "a"},
	{FlexLegacy, 1, []Constraint{Ratio(1, 4)}, "a"},
	{FlexLegacy, 1, []Constraint{Ratio(1, 2)}, "a"},
	{FlexLegacy, 1, []Constraint{Ratio(9, 10)}, "a"},
	{FlexLegacy, 1, []Constraint{Ratio(1, 1)}, "a"},
	{FlexLegacy, 1, []Constraint{Ratio(2, 1)}, "a"},
	{FlexLegacy, 2, []Constraint{Ratio(0, 1)}, "aa"},
	{FlexLegacy, 2, []Constraint{Ratio(1, 10)}, "aa"},
	{FlexLegacy, 2, []Constraint{Ratio(1, 4)}, "aa"},
	{FlexLegacy, 2, []Constraint{Ratio(1, 2)}, "aa"},
	{FlexLegacy, 2, []Constraint{Ratio(2, 3)}, "aa"},
	{FlexLegacy, 2, []Constraint{Ratio(1, 1)}, "aa"},
	{FlexLegacy, 2, []Constraint{Ratio(2, 1)}, "aa"},
	{FlexLegacy, 1, []Constraint{Ratio(0, 1), Ratio(0, 1)}, "b"},
	{FlexLegacy, 1, []Constraint{Ratio(0, 1), Ratio(1, 10)}, "b"},
	{FlexLegacy, 1, []Constraint{Ratio(0, 1), Ratio(1, 2)}, "b"},
	{FlexLegacy, 1, []Constraint{Ratio(0, 1), Ratio(9, 10)}, "b"},
	{FlexLegacy, 1, []Constraint{Ratio(0, 1), Ratio(1, 1)}, "b"},
	{FlexLegacy, 1, []Constraint{Ratio(0, 1), Ratio(2, 1)}, "b"},
	{FlexLegacy, 1, []Constraint{Ratio(1, 10), Ratio(0, 1)}, "b"},
	{FlexLegacy, 1, []Constraint{Ratio(1, 10), Ratio(1, 10)}, "b"},
	{FlexLegacy, 1, []Constraint{Ratio(1, 10), Ratio(1, 2)}, "b"},
	{FlexLegacy, 1, []Constraint{Ratio(1, 10), Ratio(9, 10)}, "b"},
	{FlexLegacy, 1, []Constraint{Ratio(1, 10), Ratio(1, 1)}, "b"},
	{FlexLegacy, 1, []Constraint{Ratio(1, 10), Ratio(2, 1)}, "b"},
	{FlexLegacy, 1, []Constraint{Ratio(1, 2), Ratio(0, 1)}, "a"},
	{FlexLegacy, 1, []Constraint{Ratio(1, 2), Ratio(1, 2)}, "a"},
	{FlexLegacy, 1, []Constraint{Ratio(1, 2), Ratio(1, 1)}, "a"},
	{FlexLegacy, 1, []Constraint{Ratio(1, 2), Ratio(2, 1)}, "a"},
	{FlexLegacy, 1, []Constraint{Ratio(9, 10), Ratio(0, 1)}, "a"},
	{FlexLegacy, 1, []Constraint{Ratio(9, 10), Ratio(1, 2)}, "a"},
	{FlexLegacy, 1, []Constraint{Ratio(9, 10), Ratio(1, 1)}, "a"},
	{FlexLegacy, 1, []Constraint{Ratio(9, 10), Ratio(2, 1)}, "a"},
	{FlexLegacy, 1, []Constraint{Ratio(1, 1), Ratio(0, 1)}, "a"},
	{FlexLegacy, 1, []Constraint{Ratio(1, 1), Ratio(1, 2)}, "a"},
	{FlexLegacy, 1, []Constraint{Ratio(1, 1), Ratio(1, 1)}, "a"},
	{FlexLegacy, 1, []Constraint{Ratio(1, 1), Ratio(2, 1)}, "a"},
	{FlexLegacy, 2, []Constraint{Ratio(0, 1), Ratio(0, 1)}, "bb"},
	{FlexLegacy, 2, []Constraint{Ratio(0, 1), Ratio(1, 4)}, "bb"},
	{FlexLegacy, 2, []Constraint{Ratio(0, 1), Ratio(1, 2)}, "bb"},
	{FlexLegacy, 2, []Constraint{Ratio(0, 1), Ratio(1, 1)}, "bb"},
	{FlexLegacy, 2, []Constraint{Ratio(0, 1), Ratio(2, 1)}, "bb"},
	{FlexLegacy, 2, []Constraint{Ratio(1, 10), Ratio(0, 1)}, "bb"},
	{FlexLegacy, 2, []Constraint{Ratio(1, 10), Ratio(1, 4)}, "bb"},
	{FlexLegacy, 2, []Constraint{Ratio(1, 10), Ratio(1, 2)}, "bb"},
	{FlexLegacy, 2, []Constraint{Ratio(1, 10), Ratio(1, 1)}, "bb"},
	{FlexLegacy, 2, []Constraint{Ratio(1, 10), Ratio(2, 1)}, "bb"},
	{FlexLegacy, 2, []Constraint{Ratio(1, 4), Ratio(0, 1)}, "ab"},
	{FlexLegacy, 2, []Constraint{Ratio(1, 4), Ratio(1, 4)}, "ab"},
	{FlexLegacy, 2, []Constraint{Ratio(1, 4), Ratio(1, 2)}, "ab"},
	{FlexLegacy, 2, []Constraint{Ratio(1, 4), Ratio(1, 1)}, "ab"},
	{FlexLegacy, 2, []Constraint{Ratio(1, 4), Ratio(2, 1)}, "ab"},
	{FlexLegacy, 2, []Constraint{Ratio(1, 3), Ratio(0, 1)}, "ab"},
	{FlexLegacy, 2, []Constraint{Ratio(1, 3), Ratio(1, 4)}, "ab"},
	{FlexLegacy, 2, []Constraint{Ratio(1, 3), Ratio(1, 2)}, "ab"},
	{FlexLegacy, 2, []Constraint{Ratio(1, 3), Ratio(1, 1)}, "ab"},
	{FlexLegacy, 2, []Constraint{Ratio(1, 3), Ratio(2, 1)}, "ab"},
	{FlexLegacy, 2, []Constraint{Ratio(1, 2), Ratio(0, 1)}, "ab"},
	{FlexLegacy, 2, []Constraint{Ratio(1, 2), Ratio(1, 2)}, "ab"},
	{FlexLegacy, 2, []Constraint{Ratio(1, 2), Ratio(1, 1)}, "ab"},
	{FlexLegacy, 2, []Constraint{Ratio(1, 1), Ratio(0, 1)}, "aa"},
	{FlexLegacy, 2, []Constraint{Ratio(1, 1), Ratio(1, 2)}, "aa"},
	{FlexLegacy, 2, []Constraint{Ratio(1, 1), Ratio(1, 1)}, "aa"},
	{FlexLegacy, 3, []Constraint{Ratio(1, 3), Ratio(1, 3)}, "abb"},
	{FlexLegacy, 3, []Constraint{Ratio(1, 3), Ratio(2, 3)}, "abb"},
	{FlexLegacy, 10, []Constraint{Ratio(0, 1), Ratio(0, 1)}, "bbbbbbbbbb"},
	{FlexLegacy, 10, []Constraint{Ratio(0, 1), Ratio(1, 4)}, "bbbbbbbbbb"},
	{FlexLegacy, 10, []Constraint{Ratio(0, 1), Ratio(1, 2)}, "bbbbbbbbbb"},
	{FlexLegacy, 10, []Constraint{Ratio(0, 1), Ratio(1, 1)}, "bbbbbbbbbb"},
	{FlexLegacy, 10, []Constraint{Ratio(0, 1), Ratio(2, 1)}, "bbbbbbbbbb"},
	{FlexLegacy, 10, []Constraint{Ratio(1, 10), Ratio(0, 1)}, "abbbbbbbbb"},
	{FlexLegacy, 10, []Constraint{Ratio(1, 10), Ratio(1, 4)}, "abbbbbbbbb"},
	{FlexLegacy, 10, []Constraint{Ratio(1, 10), Ratio(1, 2)}, "abbbbbbbbb"},
	{FlexLegacy, 10, []Constraint{Ratio(1, 10), Ratio(1, 1)}, "abbbbbbbbb"},
	{FlexLegacy, 10, []Constraint{Ratio(1, 10), Ratio(2, 1)}, "abbbbbbbbb"},
	{FlexLegacy, 10, []Constraint{Ratio(1, 4), Ratio(0, 1)}, "aaabbbbbbb"},
	{FlexLegacy, 10, []Constraint{Ratio(1, 4), Ratio(1, 4)}, "aaabbbbbbb"},
	{FlexLegacy, 10, []Constraint{Ratio(1, 4), Ratio(1, 2)}, "aaabbbbbbb"},
	{FlexLegacy, 10, []Constraint{Ratio(1, 4), Ratio(1, 1)}, "aaabbbbbbb"},
	{FlexLegacy, 10, []Constraint{Ratio(1, 4), Ratio(2, 1)}, "aaabbbbbbb"},
	{FlexLegacy, 10, []Constraint{Ratio(1, 3), Ratio(0, 1)}, "aaabbbbbbb"},
	{FlexLegacy, 10, []Constraint{Ratio(1, 3), Ratio(1, 4)}, "aaabbbbbbb"},
	{FlexLegacy, 10, []Constraint{Ratio(1, 3), Ratio(1, 2)}, "aaabbbbbbb"},
	{FlexLegacy, 10, []Constraint{Ratio(1, 3), Ratio(1, 1)}, "aaabbbbbbb"},
	{FlexLegacy, 10, []Constraint{Ratio(1, 3), Ratio(2, 1)}, "aaabbbbbbb"},
	{FlexLegacy, 10, []Constraint{Ratio(1, 2), Ratio(0, 1)}, "aaaaabbbbb"},
	{FlexLegacy, 10, []Constraint{Ratio(1, 2), Ratio(1, 2)}, "aaaaabbbbb"},
	{FlexLegacy, 10, []Constraint{Ratio(1, 2), Ratio(1, 1)}, "aaaaabbbbb"},
	{FlexLegacy, 10, []Constraint{Ratio(1, 1), Ratio(0, 1)}, "aaaaaaaaaa"},
	{FlexLegacy, 10, []Constraint{Ratio(1, 1), Ratio(1, 2)}, "aaaaaaaaaa"},
	{FlexLegacy, 10, []Constraint{Ratio(1, 1), Ratio(1, 1)}, "aaaaaaaaaa"},
	{FlexStart, 10, []Constraint{Ratio(0, 1), Ratio(0, 1)}, "          "},
	{FlexStart, 10, []Constraint{Ratio(0, 1), Ratio(1, 4)}, "bbb       "},
	{FlexStart, 10, []Constraint{Ratio(0, 1), Ratio(1, 2)}, "bbbbb     "},
	{FlexStart, 10, []Constraint{Ratio(0, 1), Ratio(1, 1)}, "bbbbbbbbbb"},
	{FlexStart, 10, []Constraint{Ratio(0, 1), Ratio(2, 1)}, "bbbbbbbbbb"},
	{FlexStart, 10, []Constraint{Ratio(1, 10), Ratio(0, 1)}, "a         "},
	{FlexStart, 10, []Constraint{Ratio(1, 10), Ratio(1, 4)}, "abbb      "},
	{FlexStart, 10, []Constraint{Ratio(1, 10), Ratio(1, 2)}, "abbbbb    "},
	{FlexStart, 10, []Constraint{Ratio(1, 10), Ratio(1, 1)}, "abbbbbbbbb"},
	{FlexStart, 10, []Constraint{Ratio(1, 10), Ratio(2, 1)}, "abbbbbbbbb"},
	{FlexStart, 10, []Constraint{Ratio(1, 4), Ratio(0, 1)}, "aaa       "},
	{FlexStart, 10, []Constraint{Ratio(1, 4), Ratio(1, 4)}, "aaabb     "},
	{FlexStart, 10, []Constraint{Ratio(1, 4), Ratio(1, 2)}, "aaabbbbb  "},
	{FlexStart, 10, []Constraint{Ratio(1, 4), Ratio(1, 1)}, "aaabbbbbbb"},
	{FlexStart, 10, []Constraint{Ratio(1, 4), Ratio(2, 1)}, "aaabbbbbbb"},
	{FlexStart, 10, []Constraint{Ratio(1, 3), Ratio(0, 1)}, "aaa       "},
	{FlexStart, 10, []Constraint{Ratio(1, 3), Ratio(1, 4)}, "aaabbb    "},
	{FlexStart, 10, []Constraint{Ratio(1, 3), Ratio(1, 2)}, "aaabbbbb  "},
	{FlexStart, 10, []Constraint{Ratio(1, 3), Ratio(1, 1)}, "aaabbbbbbb"},
	{FlexStart, 10, []Constraint{Ratio(1, 3), Ratio(2, 1)}, "aaabbbbbbb"},
	{FlexStart, 10, []Constraint{Ratio(1, 2), Ratio(0, 1)}, "aaaaa     "},
	{FlexStart, 10, []Constraint{Ratio(1, 2), Ratio(1, 2)}, "aaaaabbbbb"},
	{FlexStart, 10, []Constraint{Ratio(1, 2), Ratio(1, 1)}, "aaaaabbbbb"},
	{FlexStart, 10, []Constraint{Ratio(1, 1), Ratio(0, 1)}, "aaaaaaaaaa"},
	{FlexStart, 10, []Constraint{Ratio(1, 1), Ratio(1, 2)}, "aaaaabbbbb"},
	{FlexStart, 10, []Constraint{Ratio(1, 1), Ratio(1, 1)}, "aaaaabbbbb"},
	{FlexStart, 10, []Constraint{Ratio(1, 1), Ratio(2, 1)}, "aaaaabbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Ratio(0, 1), Ratio(0, 1)}, "          "},
	{FlexSpaceBetween, 10, []Constraint{Ratio(0, 1), Ratio(1, 4)}, "        bb"},
	{FlexSpaceBetween, 10, []Constraint{Ratio(0, 1), Ratio(1, 2)}, "     bbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Ratio(0, 1), Ratio(1, 1)}, "bbbbbbbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Ratio(0, 1), Ratio(2, 1)}, "bbbbbbbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Ratio(1, 10), Ratio(0, 1)}, "a         "},
	{FlexSpaceBetween, 10, []Constraint{Ratio(1, 10), Ratio(1, 4)}, "a       bb"},
	{FlexSpaceBetween, 10, []Constraint{Ratio(1, 10), Ratio(1, 2)}, "a    bbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Ratio(1, 10), Ratio(1, 1)}, "abbbbbbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Ratio(1, 10), Ratio(2, 1)}, "abbbbbbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Ratio(1, 4), Ratio(0, 1)}, "aaa       "},
	{FlexSpaceBetween, 10, []Constraint{Ratio(1, 4), Ratio(1, 4)}, "aaa     bb"},
	{FlexSpaceBetween, 10, []Constraint{Ratio(1, 4), Ratio(1, 2)}, "aaa  bbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Ratio(1, 4), Ratio(1, 1)}, "aaabbbbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Ratio(1, 4), Ratio(2, 1)}, "aaabbbbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Ratio(1, 3), Ratio(0, 1)}, "aaa       "},
	{FlexSpaceBetween, 10, []Constraint{Ratio(1, 3), Ratio(1, 4)}, "aaa     bb"},
	{FlexSpaceBetween, 10, []Constraint{Ratio(1, 3), Ratio(1, 2)}, "aaa  bbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Ratio(1, 3), Ratio(1, 1)}, "aaabbbbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Ratio(1, 3), Ratio(2, 1)}, "aaabbbbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Ratio(1, 2), Ratio(0, 1)}, "aaaaa     "},
	{FlexSpaceBetween, 10, []Constraint{Ratio(1, 2), Ratio(1, 2)}, "aaaaabbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Ratio(1, 2), Ratio(1, 1)}, "aaaaabbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Ratio(1, 1), Ratio(0, 1)}, "aaaaaaaaaa"},
	{FlexSpaceBetween, 10, []Constraint{Ratio(1, 1), Ratio(1, 2)}, "aaaaabbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Ratio(1, 1), Ratio(1, 1)}, "aaaaabbbbb"},
	{FlexSpaceBetween, 10, []Constraint{Ratio(1, 1), Ratio(2, 1)}, "aaaaabbbbb"},
}
